name: client_code_generators
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Paulo-Lopes-Estevao/client-code-generators

topics:
  - code-generators
  - client

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
