name: client_code_generators
description: Converts HTTP requests into different languages of your choice, generating HTTP request code for the same language.
version: 0.1.0
repository: https://github.com/Paulo-Lopes-Estevao/client-code-generators

topics:
  - code-generators
  - client

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

# Add regular dependencies here.
dependencies: 
  http: ^0.13.6
  test: ^1.21.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
